// Generated by packages/mobile-design/scripts/generate.mjs. Do not edit.
import SwiftUI

/// Semantic colors derived from packages/desktop-ui/src/peppy-tokens.css.
struct PeppyColorScheme {
    let SurfaceDesk: Color
    let SurfaceChrome: Color
    let SurfacePanel: Color
    let SurfaceEditor: Color
    let SurfaceWidget: Color
    let SurfaceHover: Color
    let SurfaceActive: Color
    let SurfaceInput: Color
    let Border: Color
    let BorderStrong: Color
    let TextPrimary: Color
    let TextStrong: Color
    let TextSecondary: Color
    let TextMuted: Color
    let Accent: Color
    let AccentHover: Color
    let AccentText: Color
    let Success: Color
    let Error: Color
    let ErrorText: Color
    let WarningText: Color
    let Focus: Color
    let FocusRing: Color
    let Primary: Color
    let PrimaryText: Color
}

enum PeppyTokens {
  static let dark = PeppyColorScheme(
      SurfaceDesk: Color(argb: 0xFF252526),
      SurfaceChrome: Color(argb: 0xFF181818),
      SurfacePanel: Color(argb: 0xFF181818),
      SurfaceEditor: Color(argb: 0xFF1F1F1F),
      SurfaceWidget: Color(argb: 0xFF202020),
      SurfaceHover: Color(argb: 0xFF2A2D2E),
      SurfaceActive: Color(argb: 0xFF313131),
      SurfaceInput: Color(argb: 0xFF1F1F1F),
      Border: Color(argb: 0xFF2B2B2B),
      BorderStrong: Color(argb: 0xFF3C3C3C),
      TextPrimary: Color(argb: 0xFFCCCCCC),
      TextStrong: Color(argb: 0xFFFFFFFF),
      TextSecondary: Color(argb: 0xFF9D9D9D),
      TextMuted: Color(argb: 0xFF8C8C8C),
      Accent: Color(argb: 0xFF0078D4),
      AccentHover: Color(argb: 0xFF026EC1),
      AccentText: Color(argb: 0xFFFFFFFF),
      Success: Color(argb: 0xFF89D185),
      Error: Color(argb: 0xFFF48771),
      ErrorText: Color(argb: 0xFFF48771),
      WarningText: Color(argb: 0xFFF2CC60),
      Focus: Color(argb: 0xFF0078D4),
      FocusRing: Color(argb: 0xFF0078D4),
      Primary: Color(argb: 0xFF0078D4),
      PrimaryText: Color(argb: 0xFFFFFFFF)
  )
  static let light = PeppyColorScheme(
      SurfaceDesk: Color(argb: 0xFFF3F3F3),
      SurfaceChrome: Color(argb: 0xFFF8F8F8),
      SurfacePanel: Color(argb: 0xFFF8F8F8),
      SurfaceEditor: Color(argb: 0xFFFFFFFF),
      SurfaceWidget: Color(argb: 0xFFFFFFFF),
      SurfaceHover: Color(argb: 0xFFF3F3F3),
      SurfaceActive: Color(argb: 0xFFECECEC),
      SurfaceInput: Color(argb: 0xFFFFFFFF),
      Border: Color(argb: 0xFFE5E5E5),
      BorderStrong: Color(argb: 0xFFCECECE),
      TextPrimary: Color(argb: 0xFF3B3B3B),
      TextStrong: Color(argb: 0xFF1F1F1F),
      TextSecondary: Color(argb: 0xFF616161),
      TextMuted: Color(argb: 0xFF616161),
      Accent: Color(argb: 0xFF005FB8),
      AccentHover: Color(argb: 0xFF0258A8),
      AccentText: Color(argb: 0xFFFFFFFF),
      Success: Color(argb: 0xFF2E7D32),
      Error: Color(argb: 0xFFC72E0F),
      ErrorText: Color(argb: 0xFFC72E0F),
      WarningText: Color(argb: 0xFF7A5200),
      Focus: Color(argb: 0xFF005FB8),
      FocusRing: Color(argb: 0xFF005FB8),
      Primary: Color(argb: 0xFF005FB8),
      PrimaryText: Color(argb: 0xFFFFFFFF)
  )

  static func colors(for colorScheme: ColorScheme) -> PeppyColorScheme {
    colorScheme == .dark ? dark : light
  }
}

private extension Color {
  init(argb: UInt32) {
    self.init(.sRGB, red: Double((argb >> 16) & 0xff) / 255, green: Double((argb >> 8) & 0xff) / 255, blue: Double(argb & 0xff) / 255, opacity: Double((argb >> 24) & 0xff) / 255)
  }
}
