#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { catalog } from "../src/catalog.mjs";
import { kotlinNames, semanticTokens, swiftNames } from "../src/tokens.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const cssPath = resolve(root, "packages/desktop-ui/src/peppy-tokens.css");
const androidTokens = resolve(root, "apps/android/app/src/main/java/dev/peppy/mobile/ui/theme/PeppyTokens.kt");
const androidStrings = resolve(root, "apps/android/app/src/main/res/values/strings_peppy.xml");
const hero = resolve(root, "apps/android/app/src/main/res/drawable/peppy_hero.xml");
const iosTokens = resolve(root, "apps/ios/PeppyMobile/Design/PeppyTokens.swift");
const iosStrings = resolve(root, "apps/ios/PeppyMobile/Peppy.xcstrings");
const generated = [androidTokens, androidStrings, hero, iosTokens, iosStrings];

function extractTheme(css, selector) {
  const start = css.indexOf(selector);
  if (start < 0) throw new Error(`Missing ${selector} in ${cssPath}`);
  const body = css.slice(start, css.indexOf("}", start));
  return Object.fromEntries([...body.matchAll(/--peppy-([\w-]+):\s*([^;]+);/g)].map(([, key, value]) => [key, value.trim()]));
}

function color(value) {
  const hex = value.replace(/^#/, "");
  if (/^[0-9a-f]{3}$/i.test(hex)) return `FF${[...hex].map(char => char + char).join("").toUpperCase()}`;
  if (/^[0-9a-f]{6}$/i.test(hex)) return `FF${hex.toUpperCase()}`;
  throw new Error(`Mobile semantic token must be hex, received ${value}`);
}

function selected(theme) {
  return Object.fromEntries(semanticTokens.map(key => {
    if (!theme[key]) throw new Error(`Missing --peppy-${key}`);
    return [key, color(theme[key])];
  }));
}

function kotlin(theme) {
  const rows = Object.entries(theme).map(([key, value]) => `    val ${kotlinNames[key]} = Color(0x${value})`).join("\n");
  return `// Generated by packages/mobile-design/scripts/generate.mjs. Do not edit.\npackage dev.peppy.mobile.ui.theme\n\nimport androidx.compose.runtime.Immutable\nimport androidx.compose.ui.graphics.Color\n\n/** Semantic colors derived from packages/desktop-ui/src/peppy-tokens.css. */\n@Immutable\ndata class PeppyColorScheme(\n${semanticTokens.map(key => `    val ${kotlinNames[key]}: Color,`).join("\n")}\n)\n\nobject PeppyTokens {\n  val Dark = PeppyColorScheme(\n${semanticTokens.map(key => `    ${kotlinNames[key]} = Color(0x${theme.dark[key]}),`).join("\n")}\n  )\n  val Light = PeppyColorScheme(\n${semanticTokens.map(key => `    ${kotlinNames[key]} = Color(0x${theme.light[key]}),`).join("\n")}\n  )\n}\n`;
}

function swift(theme) {
  const field = key => `    let ${swiftNames[key]}: Color`;
  const value = (scheme, key) => `      ${swiftNames[key]}: Color(argb: 0x${scheme[key]})`;
  return `// Generated by packages/mobile-design/scripts/generate.mjs. Do not edit.\nimport SwiftUI\n\n/// Semantic colors derived from packages/desktop-ui/src/peppy-tokens.css.\nstruct PeppyColorScheme {\n${semanticTokens.map(field).join("\n")}\n}\n\nenum PeppyTokens {\n  static let dark = PeppyColorScheme(\n${semanticTokens.map(key => value(theme.dark, key)).join(",\n")}\n  )\n  static let light = PeppyColorScheme(\n${semanticTokens.map(key => value(theme.light, key)).join(",\n")}\n  )\n\n  static func colors(for colorScheme: ColorScheme) -> PeppyColorScheme {\n    colorScheme == .dark ? dark : light\n  }\n}\n\nprivate extension Color {\n  init(argb: UInt32) {\n    self.init(.sRGB, red: Double((argb >> 16) & 0xff) / 255, green: Double((argb >> 8) & 0xff) / 255, blue: Double(argb & 0xff) / 255, opacity: Double((argb >> 24) & 0xff) / 255)\n  }\n}\n`;
}

function xmlEscape(value) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "\\\""); }
function androidCopy() { return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by packages/mobile-design/scripts/generate.mjs. Do not edit. -->\n<resources>\n${Object.entries(catalog).map(([key, value]) => `    <string name="peppy_${key}">${xmlEscape(value)}</string>`).join("\n")}\n</resources>\n`; }
function iosCopy() {
  const strings = Object.fromEntries(Object.entries(catalog).map(([key, value]) => [`peppy.${key}`, { localizations: { en: { stringUnit: { state: "translated", value } } } }]));
  return `${JSON.stringify({ sourceLanguage: "en", strings, version: "1.0" }, null, 2)}\n`;
}
function artwork() { return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated first-party phone, encrypted proxy, and client artwork. -->\n<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="160dp" android:height="96dp" android:viewportWidth="160" android:viewportHeight="96">\n    <path android:fillColor="#005FB8" android:pathData="M12,18a10,10 0,0 1,10 -10h28a10,10 0,0 1,10 10v60a10,10 0,0 1,-10 10h-28a10,10 0,0 1,-10 -10zM28,15h16v4h-16zM28,75h16v4h-16z"/>\n    <path android:fillColor="#0078D4" android:pathData="M100,18a10,10 0,0 1,10 -10h28a10,10 0,0 1,10 10v60a10,10 0,0 1,-10 10h-28a10,10 0,0 1,-10 -10zM116,15h16v4h-16zM116,75h16v4h-16z"/>\n    <path android:fillColor="#89D185" android:pathData="M72,37a8,8 0,0 1,16 0v7h3a3,3 0,0 1,3 3v14a3,3 0,0 1,-3 3h-22a3,3 0,0 1,-3 -3v-14a3,3 0,0 1,3 -3h3zM78,37v7h4v-7a2,2 0,0 0,-4 0z"/>\n    <path android:strokeColor="#0078D4" android:strokeWidth="4" android:strokeLineCap="round" android:fillColor="@android:color/transparent" android:pathData="M57,48L66,48M94,48L103,48"/>\n</vector>\n`; }

async function main() {
  const css = await readFile(cssPath, "utf8");
  const theme = { dark: selected(extractTheme(css, ":root,")), light: selected(extractTheme(css, ".theme-light")) };
  const output = new Map([[androidTokens, kotlin(theme)], [androidStrings, androidCopy()], [hero, artwork()], [iosTokens, swift(theme)], [iosStrings, iosCopy()]]);
  if (process.argv.includes("--check")) {
    const stale = [...output].filter(([path, content]) => !existsSync(path) || readFileSync(path, "utf8") !== content).map(([path]) => path);
    if (stale.length) throw new Error(`Generated mobile design files are stale:\n${stale.join("\n")}`);
    return;
  }
  await Promise.all([...output].map(async ([path, content]) => {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, "utf8");
  }));
}

await main();
