name: Release foundation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to build
        required: true
        default: main

permissions:
  contents: read

jobs:
  development-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    with:
      ref: ${{ inputs.ref }}
